[project]
name = "engine"
version = "0.1.0"
authors = [{name = "Daniel Hollarek", email = "daniel.hollarek@googlemail.com"}]
dependencies = ["distro", "func_timeout", "requests", "tiktoken", "flask", "openai", "json_repair", "pillow", "libtmux", "pylint", "flask_socketio", "fuzzywuzzy", "holytools @ git+https://git@github.com/Somerandomguy10111/holytools.git", "pyscrape @ git+https://git@github.com/Somerandomguy10111/pyscrape.git", "python-Levenshtein"]

[tool.setuptools.packages.find]
include = ["engine*", "eval*"]

[tool.deptry.per_rule_ignores]
DEP002 = ["python-Levenshtein"]
