from engine.l3_aos import Browser
from engine.l3_aos.tools import ToolCall
from tests.credtest import CredentialDependentTest

# ----------------------------------------------------------------

class BrowserTest(CredentialDependentTest):
    def setUp(self):
        self.beaver_test = 'https://en.wikipedia.org/wiki/Beaver'
        self.lightning_site = 'https://lightning.ai/docs/pytorch/stable'
        self.browser : Browser = Browser(google_api_key=self.google_apikey, searchengine_id=self.searchengine_id)

    def test_visit(self):
        self.browser.open(url=self.beaver_test)
        beaver_text = self.browser.get_text()
        print(f'Browser context after opening wikipedia {beaver_text[:1000]}...')
        self.assertIn('beaver', beaver_text.lower())
        self.assertTrue(f'/wiki/Talk:Beaver'.lower() in beaver_text.lower())

        self.browser.open(url=self.lightning_site)
        lightning_text = self.browser.get_text()
        self.assertIn('lightning', lightning_text.lower())
        self.assertIn(self.lightning_site, lightning_text.lower())

    def test_search(self):
        self.browser.open(url=f'search://wikipedia beavers')
        browser_context = self.browser.get_text()
        print(f'Browser context after search =\n {browser_context}')
        self.assertIn('Search engine', browser_context)
        self.assertTrue(f'https://en.wikipedia.org/wiki/Beaver' in browser_context)

    def tearDown(self):
        self.browser.emulator.quit()


if __name__ == "__main__":
    BrowserTest.execute_all()

















## Text wrapping test

# text = """
# Duration: 59 seconds.
# Eurasian beavers swimming and foraging
# Beavers live in [freshwater ecosystems](/wiki/Freshwater_ecosystems "Freshwater ecosystems") such as rivers, streams, lakes and ponds. Water is the most important component of beaver habitat; they swim and dive in it, and it provides them refuge from land predators. It also restricts access to their homes and allows them to move building objects more easily. Beavers prefer slower moving streams, typically with a [gradient](/wiki/Stream_gradient "Stream gradient") (steepness) of one percent, though they have been recorded using streams with gradients as high as 15 percent. Beavers are found in wider streams more often than in narrower ones. They also prefer areas with no regular flooding and may abandon a location for years after a significant flood.[[47]](#cite_note-FOOTNOTEMüller-SchwarzeSun2003107,_109-47)
# Beavers typically select flat landscapes with diverse vegetation close to the water. North American beavers prefer trees being 60 m (200 ft) or less from the water, but will roam several hundred meters to find more. Beavers have also been recorded in mountainous areas. [Dispersing](/wiki/Biological_dispersal "Biological dispersal") beavers will use certain habitats temporarily before finding their ideal home. These include small streams, temporary swamps, ditches, and backyards. These sites lack important resources, so the animals do not stay there permanently. Beavers have increasingly settled at or near human-made environments, including agricultural areas, [suburbs](/wiki/Suburbs "Suburbs"), [golf courses](/wiki/Golf_courses "Golf courses"), and shopping malls.[[48]](#cite_note-FOOTNOTEMüller-SchwarzeSun2003106–110-48)
# [![Beaver in water eating lily pads](//upload.wikimedia.org/wikipedia/commons/thumb/1/15/Beaver_Eating_Lilly_Pads_%2815682458379%29.jpg/220px-Beaver_Eating_Lilly_Pads_%2815682458379%29.jpg)](/wiki/File:Beaver_Eating_Lilly_Pads_(15682458379).jpg)
# North American beaver eating lily pads
# Beavers have an [herbivorous](/wiki/Herbivorous "Herbivorous") and a [generalist](/wiki/Generalist_and_specialist_species "Generalist and specialist species") diet. During the spring and summer, they mainly feed on herbaceous plant material such as leaves, roots, herbs, ferns, grasses, [sedges](/wiki/Sedges "Sedges"), [water lilies](/wiki/Nymphaea "Nymphaea"), [water shields](/wiki/Brasenia "Brasenia"), [rushes](/wiki/Scirpus "Scirpus"), and [cattails](/wiki/Typha "Typha"). During the fall and winter, they eat more [bark](/wiki/Bark_(botany) "Bark (botany)") and [cambium](/wiki/Cambium "Cambium") of woody plants; tree and shrub species consumed include [aspen](/wiki/Aspen "Aspen"), [birch](/wiki/Birch "Birch"), [oak](/wiki/Oak "Oak"), [dogwood](/wiki/Dogwood "Dogwood"), [willow](/wiki/Willow "Willow") and [alder](/wiki/Alder "Alder").[[9]](#cite_note-MacDonald-9)[[49]](#cite_note-FOOTNOTERuntz201589-49)[[50]](#cite_note-canal-50)[[24]](#cite_note-JohnHopkins-24) There is some disagreement about why beavers select specific woody plants; some research has shown that beavers more frequently select species which are more easily digested,[[51]](#cite_note-51) while others suggest beavers principally forage based on stem size.[[52]](#cite_note-52) Beavers may [cache](/wiki/Hoarding_(animal_behavior) "Hoarding (animal behavior)") their food for the winter, piling wood in the deepest part of their pond where it cannot be reached by other [browsers](/wiki/Browsing_(herbivory) "Browsing (herbivory)"). This cache is known as a "raft"; when the top becomes frozen, it creates a "cap".[[24]](#cite_note-JohnHopkins-24)[[9]](#cite_note-MacDonald-9) The beaver accesses the raft by swimming under the ice. Many populations of Eurasian beaver do not make rafts, but forage on land during winter.[[9]](#cite_note-MacDonald-9)
# Beavers usually live up to 10 years. [Felids](/wiki/Felid "Felid"), [canids](/wiki/Canid "Canid"), and [bears](/wiki/Bears "Bears") may prey upon them. Beavers are protected from predators when in their lodges, and prefer to stay near water. Parasites of the beaver include the bacteria *[Francisella tularensis](/wiki/Francisella_tularensis "Francisella tularensis")*, which causes [tularemia](/wiki/Tularemia "Tularemia"); the protozoan *[Giardia duodenalis](/wiki/Giardia_duodenalis "Giardia duodenalis")*, which causes [giardiasis](/wiki/Giardiasis "Giardiasis") (beaver fever); and the [beaver beetle](/wiki/Beaver_beetle "Beaver beetle") and [mites](/wiki/Mites "Mites") of the genus *[Schizocarpus](/w/index.php?title=Schizocarpus&action=edit&redlink=1 "Schizocarpus (page does not exist)")*.[[53]](#cite_note-FOOTNOTEMüller-SchwarzeSun200383,_113–114,_118–122-53)[[54]](#cite_note-beaverfever-54) They have also been recorded to be infected with the [rabies virus](/wiki/Rabies_virus "Rabies virus").[[55]](#cite_note-55)
# ### Infrastructure
# "Beaver lodge" redirects here. For the town in Alberta, Canada, see [Beaverlodge](/wiki/Beaverlodge "Beaverlodge").
# Further information: [Beaver dam](/wiki/Beaver_dam "Beaver dam")
# [![Beaver chewing through a tree trunk](//upload.wikimedia.org/wikipedia/commons/thumb/1/11/American_Beaver%2C_tree_cutting.jpg/220px-American_Beaver%2C_tree_cutting.jpg)](/wiki/File:American_Beaver,_tree_cutting.jpg)
# North American beaver chewing down a tree
# Beavers need trees and shrubs to use as building material for [dams](/wiki/Beaver_dam "Beaver dam"), which restrict flowing water to create a pond for them to live in, and for lodges, which act as shelters and refuges from predators and the elements. Without such material, beavers dig [burrows](/wiki/Burrow "Burrow") into a [bank](/wiki/Bank_(geography) "Bank (geography)") to live. Dam construction begins in late summer or early fall, and they repair them whenever needed. Beavers can [cut down](/wiki/Felling "Felling") trees up to 15 cm (5.9 in) wide in less than 50 minutes. Thicker trees, at 25 cm (9.8 in) wide or more, may not fall for hours.[[56]](#cite_note-FOOTNOTEMüller-SchwarzeSun200354,_56–57,_68,_108-56) When chewing down a tree, beavers switch between biting with the left and right side of the mouth. Tree branches are then cut and carried to their destination with the powerful jaw and neck muscles. Other building materials, like mud and rocks, are held by the forelimbs and tucked between the chin and chest.[[57]](#cite_note-FOOTNOTERuntz201584,_103-57)
# Beavers start building dams when they hear running water, and the sound of a leak in a dam triggers them to repair it.[[58]](#cite_note-FOOTNOTERuntz2015104-58) To build a dam, beavers stack up relatively long and thick logs between banks and in opposite directions. Heavy rocks keep them stable, and grass is packed between them. Beavers continue to pile on more material until the dam slopes in a direction facing upstream. Dams can range in height from 20 cm (7.9 in) to 3 m (9.8 ft) and can stretch from 0.3 m (1 ft 0 in) to several hundred meters long. Beaver dams are more effective in trapping and slowly leaking water than man-made concrete dams. Lake-dwelling beavers do not need to build dams.[[59]](#cite_note-FOOTNOTEMüller-SchwarzeSun200354–56,_109-59)
# [![see caption](//upload.wikimedia.org/wikipedia/commons/thumb/0/01/Beaverlodge.JPG/220px-Beaverlodge.JPG)](/wiki/File:Beaverlodge.JPG)
# Open-water beaver lodge in Canada
# Beavers make two types of lodges: bank lodges and open-water lodges. Bank lodges are burrows dug along the shore and covered in sticks. The more complex freestanding, open-water lodges are built over a platform of piled-up sticks. The lodge is mostly sealed with mud, except for a hole at the top which acts as an air vent. Both types are accessed by underwater entrances.[[24]](#cite_note-JohnHopkins-24)[[60]](#cite_note-FOOTNOTEMüller-SchwarzeSun200356–57-60) The above-water space inside the lodge is known as the "living chamber", and a "dining area" may exist close to the water entrance.[[9]](#cite_note-MacDonald-9) Families routinely clean out old plant material and bring in new material.[[61]](#cite_note-FOOTNOTEMüller-SchwarzeSun200332-61)
# North American beavers build more open-water lodges than Eurasian beavers. Beaver lodges built by new settlers are typically small and sloppy. More experienced families can build structures with a height of 2 m (6 ft 7 in) and an above-water diameter of 6 m (20 ft). A lodge sturdy enough to withstand the coming winter can be finished in just two nights. Both lodge types can be present at a beaver site. During the summer, beavers tend to use bank lodges to keep cool. They use open-water lodges during the winter. The air vent provides ventilation, and newly added carbon dioxide can be cleared in an hour. The lodge remains consistent in oxygen and carbon dioxide levels from season to season.[[62]](#cite_note-FOOTNOTEMüller-SchwarzeSun20036,_57–58-62)
# Beavers in some areas will dig canals connected to their ponds. The canals fill with groundwater and give beavers access and easier transport of resources, as well as allow them to escape predators. These canals can stretch up to 1 m (3 ft 3 in) wide, 0.5 m (1 ft 8 in) deep, and over 0.5 km (0.31 mi) long. It has been hypothesized that beavers' canals are not only transportation routes but an extension of their "[central place](/wiki/Central_place_foraging "Central place foraging")" around the lodge and/or food cache.[[50]](#cite_note-canal-50)[[63]](#cite_note-63) As they drag wood across the land, beavers leave behind trails or "slides", which they reuse when moving new material.[[24]](#cite_note-JohnHopkins-24)
# ### Environmental effects
# Main article: [Environmental impacts of beavers](/wiki/Environmental_impacts_of_beavers "Environmental impacts of beavers")
# Beaver dam enlargement[![](//upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Beaver_dam_-_geograph.org.uk_-_1452003.jpg/212px-Beaver_dam_-_geograph.org.uk_-_1452003.jpg)](/wiki/File:Beaver_dam_-_geograph.org.uk_-_1452003.jpg)September 2009[![](//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Beaver_dam_-_four_months_on_-_geograph.org.uk_-_1623430.jpg/212px-Beaver_dam_-_four_months_on_-_geograph.org.uk_-_1623430.jpg)](/wiki/File:Beaver_dam_-_four_months_on_-_geograph.org.uk_-_1623430.jpg)December 2009Images of a beaver dam over a four-month period. Dams block rivers and create ponds.
# The beaver works as an [ecosystem engineer](/wiki/Ecosystem_engineer "Ecosystem engineer") and [keystone species](/wiki/Keystone_species "Keystone species"), as its activities can have a great impact on the landscape and [biodiversity](/wiki/Biodiversity "Biodiversity") of an area. Aside from humans, few other extant animals appear to do more to shape their environment.[[64]](#cite_note-Rosell-64) When building dams, beavers alter the paths of streams and rivers, allowing for the creation of extensive [wetland](/wiki/Wetland "Wetland") habitats.[[65]](#cite_note-65) In one study, beavers were associated with large increases in open-water areas. When beavers returned to an area, 160% more open water was available during droughts than in previous years, when they were absent.[[66]](#cite_note-66) Beaver dams also lead to higher [water tables](/wiki/Water_table "Water table") in mineral soil environments and in wetlands such as [peatlands](/wiki/Fen "Fen"). In peatlands particularly, their dams stabilize the constantly changing water levels, leading to greater [carbon storage](/wiki/Carbon_sequestration "Carbon sequestration").[[67]](#cite_note-67)
# Beaver ponds, and the wetlands that succeed them, remove sediments and pollutants from waterways, and can stop the loss of important soils.[[68]](#cite_note-68)[[69]](#cite_note-69) These ponds can increase the [productivity](/wiki/Productivity_(ecology) "Productivity (ecology)") of freshwater ecosystems by accumulating [nitrogen](/wiki/Nitrogen "Nitrogen") in sediments.[[64]](#cite_note-Rosell-64) Beaver activity can affect the temperature of the water; in northern latitudes, ice thaws earlier in the warmer beaver-dammed waters.[[70]](#cite_note-ice-70) Beavers may contribute to [climate change](/wiki/Climate_change "Climate change"). In Arctic areas, the floods they create can cause [permafrost](/wiki/Permafrost "Permafrost") to thaw, [releasing methane into the atmosphere](/wiki/Arctic_methane_emissions "Arctic methane emissions").[[71]](#cite_note-71)[[72]](#cite_note-72)
# As wetlands are formed and [riparian](/wiki/Riparian "Riparian") habitats are enlarged, aquatic plants colonize the newly available watery habitat.[[64]](#cite_note-Rosell-64) One study in the [Adirondacks](/wiki/Adirondacks "Adirondacks") found that beaver engineering lead to an increase of more than 33 percent in [herbaceous plant](/wiki/Herbaceous_plant "Herbaceous plant") diversity along the water's edge.[[73]](#cite_note-73) Another study in semiarid [eastern Oregon](/wiki/Eastern_Oregon "Eastern Oregon") found that the width of riparian vegetation on stream banks increased several-fold as beaver dams watered previously dry terraces adjacent to the stream.[[74]](#cite_note-74) Riparian ecosystems in arid areas appear to sustain more plant life when beaver dams are present.[[75]](#cite_note-75) Beaver ponds act as a refuge for riverbank plants during [wildfires](/wiki/Wildfires "Wildfires"), and provide them with enough moisture to resist such fires.[[76]](#cite_note-wildfire-76) [Introduced beavers at Tierra del Fuego](/wiki/Beaver_eradication_in_Tierra_del_Fuego "Beaver eradication in Tierra del Fuego") have been responsible for destroying the indigenous forest. Unlike trees in North America, many trees in South America cannot grow back after being cut down.[[77]](#cite_note-nature-77)[[78]](#cite_note-78)
# [![](//upload.wikimedia.org/wikipedia/commons/thumb/b/be/Sockeye_salmon_jumping_over_beaver_dam_Lake_Aleknagik%2C_AK_Kristina_Ramstad_1997.jpg/170px-Sockeye_salmon_jumping_over_beaver_dam_Lake_Aleknagik%2C_AK_Kristina_Ramstad_1997.jpg)](/wiki/File:Sockeye_salmon_jumping_over_beaver_dam_Lake_Aleknagik,_AK_Kristina_Ramstad_1997.jpg)
# [Salmon](/wiki/Salmon "Salmon") (*[Oncorhynchus nerka](/wiki/Oncorhynchus_nerka "Oncorhynchus nerka")*) jumping a beaver dam
# Beaver activity impacts [communities](/wiki/Community_(ecology) "Community (ecology)") of [aquatic invertebrates](/wiki/Aquatic_invertebrate "Aquatic invertebrate"). Damming typically leads to an increase of [slow or motionless water](/wiki/Lentic_ecosystem "Lentic ecosystem") species, like [dragonflies](/wiki/Dragonflies "Dragonflies"), [oligochaetes](/wiki/Oligochaetes "Oligochaetes"), [snails](/wiki/Snails "Snails"), and [mussels](/wiki/Mussels "Mussels"). This is to the detriment of [rapid water](/wiki/Lotic_ecosystems "Lotic ecosystems") species like [black flies](/wiki/Black_flies "Black flies"), [stoneflies](/wiki/Stoneflies "Stoneflies"), and [net-spinning caddisflies](/wiki/Hydropsychidae "Hydropsychidae").[[64]](#cite_note-Rosell-64)[[79]](#cite_note-79)[[80]](#cite_note-80) Beaver floodings create more dead trees, providing more habitat for terrestrial invertebrates like *[Drosophila](/wiki/Drosophila "Drosophila")* flies and [bark beetles](/wiki/Bark_beetles "Bark beetles"), which live and breed in dead wood.[[64]](#cite_note-Rosell-64)[[81]](#cite_note-81)[[82]](#cite_note-82) The presence of beavers can increase wild [salmon](/wiki/Salmon "Salmon") and [trout](/wiki/Trout "Trout") populations, and the average size of these fishes. These species use beaver habitats for spawning, overwintering, feeding, and as havens from changes in water flow. The positive effects of beaver dams on fish appear to outweigh the negative effects, such as blocking of migration.[[83]](#cite_note-83) Beaver ponds have been shown to be beneficial to [frog](/wiki/Frog "Frog") populations by protecting areas for larvae to mature in warm water.[[84]](#cite_note-84) The stable waters of beaver ponds also provide ideal habitat for freshwater [turtles](/wiki/Turtles "Turtles").[[85]](#cite_note-85)
# Beavers help [waterfowl](/wiki/Waterfowl "Waterfowl") by creating increased areas of water. The widening of the [riparian zone](/wiki/Riparian_zone "Riparian zone") associated with beaver dams has been shown to increase the abundance and diversity of birds favoring the water's edge, an impact that may be especially important in [semi-arid climates](/wiki/Semi-arid_climate "Semi-arid climate").[[86]](#cite_note-86) Fish-eating birds use beaver ponds for foraging, and in some areas, certain species appear more frequently at sites where beavers were active than at sites with no beaver activity.[[64]](#cite_note-Rosell-64)[[87]](#cite_note-birds-87)[[88]](#cite_note-88) In a study of [Wyoming](/wiki/Wyoming "Wyoming") streams and rivers, watercourses with beavers had 75 times as many [ducks](/wiki/Ducks "Ducks") as those without.[[89]](#cite_note-89) As trees are drowned by rising beaver impoundments, they become an ideal habitat for [woodpeckers](/wiki/Woodpeckers "Woodpeckers"), which carve cavities that may be later used by other bird species.[[64]](#cite_note-Rosell-64)[[87]](#cite_note-birds-87) Beaver-caused ice thawing in northern latitudes allows [Canada geese](/wiki/Canada_geese "Canada geese") to nest earlier.[[70]](#cite_note-ice-70)
# Other semi-aquatic mammals, such as [water voles](/wiki/European_water_vole "European water vole"), [muskrats](/wiki/Muskrats "Muskrats"), [minks](/wiki/Minks "Minks"), and [otters](/wiki/Otters "Otters"), will shelter in beaver lodges.[[64]](#cite_note-Rosell-64) Beaver modifications to streams in Poland create habitats favorable to [bat](/wiki/Bat "Bat") species that forage at the water surface and "prefer moderate vegetation clutter".[[90]](#cite_note-90) Large herbivores, such as some [deer](/wiki/Deer "Deer") species, benefit from beaver activity as they can access vegetation from fallen trees and ponds.[[64]](#cite_note-Rosell-64)
# Behavior
# --------
# [![](//upload.wikimedia.org/wikipedia/commons/thumb/6/62/Beaver_family_upper_Los_Gatos_Creek_2008_Mercury_Freedom.jpg/220px-Beaver_family_upper_Los_Gatos_Creek_2008_Mercury_Freedom.jpg)](/wiki/File:Beaver_family_upper_Los_Gatos_Creek_2008_Mercury_Freedom.jpg)North American beaver family, with the center pair grooming one another[![](//upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Tayside_Beaver_mother_and_kit_June_5%2C_2010_Ray_Scott.jpg/220px-Tayside_Beaver_mother_and_kit_June_5%2C_2010_Ray_Scott.jpg)](/wiki/File:Tayside_Beaver_mother_and_kit_June_5,_2010_Ray_Scott.jpg)Eurasian beaver parent and kit
# Beavers are mainly [nocturnal](/wiki/Nocturnality "Nocturnality") and [crepuscular](/wiki/Crepuscular_animal "Crepuscular animal"), and spend the daytime in their shelters. In northern latitudes, beaver activity is decoupled from the [24-hour cycle](/wiki/Circadian_rhythm "Circadian rhythm") during the winter, and may last as long as 29 hours. They do not [hibernate](/wiki/Hibernate "Hibernate") during winter, and spend much of their time in their lodges.[[9]](#cite_note-MacDonald-9)[[24]](#cite_note-JohnHopkins-24)[[91]](#cite_note-FOOTNOTERuntz201576-91)
# ### Family life
# The core of beaver social organization is the family, which is composed of an adult male and an adult female in a [monogamous pair](/wiki/Pair_bond "Pair bond") and their offspring.[[9]](#cite_note-MacDonald-9)[[31]](#cite_note-Pelagic-31) Beaver families can have as many as ten members; groups about this size require multiple lodges.[[92]](#cite_note-FOOTNOTEMüller-SchwarzeSun200330–31-92) [Mutual grooming](/wiki/Mutual_grooming "Mutual grooming") and play fighting maintain bonds between family members, and aggression between them is uncommon.[[31]](#cite_note-Pelagic-31)
# Adult beavers mate with their partners, though partner replacement appears to be common. A beaver that loses its partner will wait for another one to come by. [Estrus](/wiki/Estrus "Estrus") cycles begin in late December and peak in mid-January. Females may have two to four estrus cycles per season, each lasting 12–24 hours. The pair typically mate in the water and to a lesser extent in the lodge, for half a minute to three minutes.[[93]](#cite_note-FOOTNOTEMüller-SchwarzeSun200380,_85-93)
# Up to four young, or kits, are born in spring and summer, after a three or four-month [gestation](/wiki/Gestation "Gestation").[[31]](#cite_note-Pelagic-31)[[94]](#cite_note-FOOTNOTEMüller-SchwarzeSun200380-94) Newborn beavers are [precocial](/wiki/Precocial "Precocial") with a full fur coat, and can open their eyes within days of birth.[[24]](#cite_note-JohnHopkins-24)[[31]](#cite_note-Pelagic-31) Their mother is the primary caretaker, while their father maintains the territory.[[9]](#cite_note-MacDonald-9) Older siblings from a previous litter also play a role.[[95]](#cite_note-FOOTNOTEMüller-SchwarzeSun200332–33-95)
# After they are born, the kits spend their first one to two months in the lodge. Kits suckle for as long as three months, but can eat solid food within their second week and rely on their parents and older siblings to bring it to them. Eventually, beaver kits explore outside the lodge and forage on their own, but may follow an older relative and hold onto their backs.[[31]](#cite_note-Pelagic-31) After their first year, young beavers help their families with construction.[[9]](#cite_note-MacDonald-9) Beavers sexually mature around 1.5–3 years.[[24]](#cite_note-JohnHopkins-24) They become independent at two years old, but remain with their parents for an extra year or more during times of food shortage, high population density, or drought.[[96]](#cite_note-FOOTNOTEMüller-SchwarzeSun2003332–333,_100–101-96)[[97]](#cite_note-97)
# ### Territories and spacing
# [![A beaver on a water bank](//upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Castor_fiber_vistulanus2.jpg/220px-Castor_fiber_vistulanus2.jpg)](/wiki/File:Castor_fiber_vistulanus2.jpg)
# [Eurasian beave"""
#
# stripped_lines = text.split('\n')
#
# max_width = 100
# compacted_lines = []
# for line in stripped_lines:
#     if len(line) <= max_width:
#         compacted_lines.append(line)
#     else:
#         no_lines = len(line) // max_width + 1 if len(line) % max_width > 0 else 0 # == math.ciel
#         remain = line
#         for _ in range(no_lines):
#             compacted_lines.append(remain[:max_width])
#             remain = remain[max_width:]
#
# compacted_text = '\n'.join(compacted_lines)
#
# print(compacted_text)
#
# single_line = text.replace('\n', '')
# compacted_single_line = compacted_text.replace('\n', '')
# assert single_line == compacted_single_line